import React,{useEffect,useState} from 'react';import ReactDOM from 'react-dom/client';import {BrowserRouter,Routes,Route,Navigate,Link,useNavigate} from 'react-router-dom';import axios from 'axios';
axios.defaults.baseURL='http://localhost:5000';axios.defaults.withCredentials=true;
const roles={super_admin:'/dashboard/super-admin',admin:'/dashboard/admin',waiter:'/dashboard/waiter'} as any;
function Login(){const n=useNavigate();const [email,setE]=useState('');const [password,setP]=useState('');const login=async()=>{const u=(await axios.post('/api/auth/login',{email,password})).data;n(roles[u.role]);};return <div><h1>Restaurant Control Panel</h1><input placeholder='email' value={email} onChange={e=>setE(e.target.value)}/><input placeholder='password' type='password' value={password} onChange={e=>setP(e.target.value)}/><button onClick={login}>Login</button></div>}
function Dash({role}:{role:string}){const n=useNavigate();return <div><h2>{role} dashboard</h2><Link to='/orders'>Orders</Link> <Link to='/waiter/order'>New order</Link><button onClick={async()=>{await axios.post('/api/auth/logout');n('/login')}}>Logout</button></div>}
function Orders(){const [orders,set]=useState<any[]>([]);useEffect(()=>{axios.get('/api/orders').then(r=>set(r.data));},[]);return <div>{orders.map(o=><div key={o.id}>{o.orderNumber} {o.status} {o.paymentStatus}</div>)}</div>}
function WaiterOrder(){const [products,setP]=useState<any[]>([]);const [tableNumber,setT]=useState('Table 1');const [cart,setC]=useState<any[]>([]);useEffect(()=>{axios.get('/api/products').then(r=>setP(r.data));},[]);const submit=async()=>{const items=cart.map((p:any)=>({productId:p.id,productName:p.name,quantity:1,unitPrice:p.price,totalPrice:p.price}));await axios.post('/api/orders',{tableNumber,totalPrice:items.reduce((a:number,b:any)=>a+b.totalPrice,0),items});setC([])};return <div><input value={tableNumber} onChange={e=>setT(e.target.value)}/>{products.map(p=><button key={p.id} onClick={()=>setC([...cart,p])}>{p.name}</button>)}<button disabled={!cart.length} onClick={submit}>Submit Order</button></div>}
function App(){const [me,setMe]=useState<any>(null);useEffect(()=>{axios.get('/api/auth/me').then(r=>setMe(r.data)).catch(()=>{});},[]);return <Routes><Route path='/login' element={<Login/>}/><Route path='/dashboard/super-admin' element={<Dash role='super_admin'/>}/><Route path='/dashboard/admin' element={<Dash role='admin'/>}/><Route path='/dashboard/waiter' element={<Dash role='waiter'/>}/><Route path='/orders' element={<Orders/>}/><Route path='/waiter/order' element={<WaiterOrder/>}/><Route path='*' element={<Navigate to={me?roles[me.role]:'/login'}/>}/></Routes>}
ReactDOM.createRoot(document.getElementById('root')!).render(<BrowserRouter><App/></BrowserRouter>);
